-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR

--ACESSAR SENHAS DOS USUARIOS
SELECT * FROM FDN_USERTENANT WHERE EMAIL LIKE 'eduardo.d%'

--IR EM SITE DE CONVERSÃO DE SENHAS MD5 E CRIAR NOVA SENHA, SUBSTITUIR PELO COMANDO ABAIXO NO USUÁRIO DESEJADO

/* COMENTADO POR SEGURANÇA - O PASSWORD ABAIXO CORRESPONDE A SENHA 'CompFluig@4169' - https://www.md5hashgenerator.com/
UPDATE FDN_USERTENANT SET [PASSWORD] = 'b9ca23dffaeb4ff0f1cceed480f84b0e' WHERE USER_TENANT_ID = 174
*/