-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR

-- CONSULTAR FORMULÁRIO PRA VERIFICAR A VERSÃO ATIVA - O DATASET PODE SER CONSULTADO PEGANDO DAS PROPRIEDADES DE UM FORMULÁRIO SALVO
SELECT NM_DATASET, NUM_VERS_PROPRIED, NR_DOCUMENTO_PAI, * FROM DOCUMENTO WHERE NM_DATASET = 'ds_aprovadores_secao' AND VERSAO_ATIVA = 1

-- ATUALIZAR TODOS OS FORMULÁRIOS PRA VERSÃO DO FORMULÁRIO PAI = PEGAR NÚMERO DO DOCUMENTO E COLOCA NO WHERE DO DOCUMENTO PAI
/*
UPDATE DOCUMENTO SET NUM_VERS_PROPRIED = 34000 WHERE NR_DOCUMENTO_PAI = '69' AND VERSAO_ATIVA = 1
*/

--CONSULTA MODIFICAÇÕES VENDO TODOS OS NR_DOCUMENTO_PAI IGUAL AO CÓDIGO ACIMA
--SELECT NM_DATASET, NUM_VERS_PROPRIED, NR_DOCUMENTO_PAI, * FROM DOCUMENTO WHERE NR_DOCUMENTO_PAI = '69' AND VERSAO_ATIVA = 1