-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR

-- CONSULTAR FORMULÁRIO PRA VERIFICAR A VERSÃO ATIVA
SELECT NUM_VERS_PROPRIED, * FROM DOCUMENTO WHERE NR_DOCUMENTO = '138787' AND VERSAO_ATIVA = 1

-- ATUALIZAR TODOS OS FORMULÁRIOS PRA VERSÃO DO FORMULÁRIO PAI
UPDATE DOCUMENTO SET NUM_VERS_PROPRIED = 10000 WHERE NR_DOCUMENTO_PAI = '138787' AND VERSAO_ATIVA = 1