-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR

SELECT * FROM HISTOR_PROCES WHERE COD_EMPRESA = 1 AND LOG_ATIV = 1 AND NUM_PROCES BETWEEN 99949 AND 101590 ORDER BY NUM_PROCES DESC

/* ATUALIZA HISTÓRICO DO PROCESSO E MUDA ULTIMA TAREFA DO PROCESSO PRA FECHADO
UPDATE HISTOR_PROCES SET LOG_ATIV = 0 WHERE COD_EMPRESA = 1 AND LOG_ATIV = 1 AND NUM_PROCES BETWEEN 99949 AND 101590;
*/
/* ALTERAR O PROCESSO PRO STATUS DE CANCELADO
UPDATE PROCES_WORKFLOW SET LOG_ATIV = 0, END_DATE = GETDATE(), [STATUS]= 1 WHERE COD_EMPRESA = 1 AND LOG_ATIV = 1 AND NUM_PROCES BETWEEN 99949 AND 101590 AND [STATUS]=0;
*/
/* ALTERAR A TAREFA (USUÁRIO, CANCELAR, ATIVAR)
UPDATE TAR_PROCES SET LOG_ATIV = 0, END_DATE = GETDATE(), [IDI_STATUS]= 1 WHERE COD_EMPRESA = 1 AND LOG_ATIV = 1 AND NUM_PROCES BETWEEN 99949 AND 101590 AND [IDI_STATUS]=0;
*/