-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR

-- ############################################ --
-- ## BUSCA DO CÓDIGO DO DOCUMENTO ONDE ESTÁ O BD PELO NOME DE UM PROCESSO -- 
USE fluig_prod SELECT * FROM PROCES_WORKFLOW WHERE COD_EMPRESA = 1 AND COD_DEF_PROCES LIKE '%cadastro_fornecedor%' ORDER BY NUM_PROCES DESC

-- ############################################ --
-- ## BUSCA DE BD POR UM PROCESSO OU FORMULÁRIO
-- * PROCESSO: BUSQUE PELO NR_DOCUMENTO_CARD_INDEX ENCONTRADO NA CONSULTA ANTERIOR
-- * FORMULÁRIO: BUSQUE PELO DATASET PRINCIAL DO FORMULÁRIO (O NOME PODE SER CONSULTADO NA EXPORTAÇÃO DO FORMULÁRIO PRO FLUIG OU CLICANDO EM PROPRIEDADES DE UM FORMULÁRIO JÁ PREENCHIDO)
USE fluig_prod SELECT COD_LISTA, * FROM DOCUMENTO WHERE COD_EMPRESA = 1 AND VERSAO_ATIVA = 1 AND NR_DOCUMENTO = 128184 -- AND NM_DATASET LIKE '%solic_cadast_func_pj%'

-- ############################################ --
-- ## BUSCA DO BD
-- * INSERE ML = TABELA + 001 = EMPRESA 001 + COD_LISTA = ENCONTRADO NA BUSCA ANTERIOR
USE fluig_prod SELECT * FROM ML001029 ORDER BY documentid DESC

-- ############################################ --
-- ## BUSCA DAS TABELA PAI X FILHO REFERENCIADAS NO BD
-- *  INSERE NO FILTRO O COD LISTA PAI PRA BUSCA DOS FILHOS
USE fluig_prod SELECT * FROM META_LISTA_REL WHERE COD_LISTA_PAI = '89'

-- ############################################ --
-- ## BUSCA DOS DADOS NAS TABELAS FILHOS (PODE HAVER VÁRIAS TABELAS)
-- * CONSULTE AS TABELA FILHO ACRESCENTANDO ML001 PRA EMPRESA 001 + CÓD TABELA FILHO
USE fluig_prod SELECT * FROM ML001117

-- ############################################ --
-- ## CONSULTA QUE RETORNA O DADO DA ULTIMA VERSÃO DO FORMULÁRIO --
USE fluig_prod 
WITH BD_DETALHES AS
(
    SELECT *,
    ROW_NUMBER() OVER(PARTITION BY documentid ORDER BY [version] DESC) AS rn
    FROM ML001089
)
SELECT
    CASE
        WHEN PROCES_WORKFLOW.STATUS = 0 THEN 'ATIVO' 
        WHEN PROCES_WORKFLOW.STATUS = 1 THEN 'CANCELADO'
        WHEN PROCES_WORKFLOW.STATUS = 2 THEN 'FINALIZADO' 
        ELSE 'N ENCONTRADO'
        END AS 'STATUS', * FROM BD_DETALHES 
LEFT JOIN PROCES_WORKFLOW ON documentid = NR_DOCUMENTO_CARD

WHERE rn = 1 ORDER BY documentid DESC

-->> OU ALTERANATIVA ABAIXO (IGUAL, ESCRITO DE FORMA DIFERNETE)
SELECT
    CASE
        WHEN PROCES_WORKFLOW.STATUS = 0 THEN 'ATIVO' 
        WHEN PROCES_WORKFLOW.STATUS = 1 THEN 'CANCELADO'
        WHEN PROCES_WORKFLOW.STATUS = 2 THEN 'FINALIZADO' 
        ELSE 'N ENCONTRADO'
        END AS 'STATUS',
        CONCAT(NR_DOCUMENTO_CARD_INDEX,' - ',NUM_VERS,' - ',COD_DEF_PROCES) AS 'FX_ID',
        *
        FROM
        (
        SELECT *,
        ROW_NUMBER() OVER(PARTITION BY documentid ORDER BY [version] DESC) AS rn
        FROM ML001048
        ) AS  BD_DETALHES
        LEFT JOIN PROCES_WORKFLOW ON documentid = NR_DOCUMENTO_CARD
        WHERE rn = 1 ORDER BY documentid DESC

-- ############################################ --
-- ## CONSULTA QUE RETORNA A ETAPA QUE ESTÁ CADA PROCESSO
SELECT
    *
    FROM
    (SELECT
    HISTOR_PROCES.NUM_PROCES,
    HISTOR_PROCES.NUM_SEQ_MOVTO,
    HISTOR_PROCES.NUM_SEQ_MOVTO_ANT,
    HISTOR_PROCES.DAT_MOVTO,
    HISTOR_PROCES.HRA_MOVTO,
    HISTOR_PROCES.NUM_SEQ_ESTADO,
    HISTOR_PROCES.NUM_SUB_PROCES,
    PROCES_WORKFLOW.COD_DEF_PROCES,
    PROCES_WORKFLOW.NR_DOCUMENTO_CARD_INDEX

    FROM HISTOR_PROCES

    LEFT JOIN
        (
            SELECT COD_DEF_PROCES, NUM_PROCES, NR_DOCUMENTO_CARD_INDEX FROM PROCES_WORKFLOW
        ) AS PROCES_WORKFLOW
            ON HISTOR_PROCES.NUM_PROCES = PROCES_WORKFLOW.NUM_PROCES

    WHERE HISTOR_PROCES.COD_EMPRESA = 1 --AND HISTOR_PROCES.NUM_PROCES = 104110
    ) AS TAB1
    LEFT JOIN
        (
            SELECT DISTINCT DES_ESTADO, COD_EMPRESA, COD_DEF_PROCES, NUM_SEQ FROM ESTADO_PROCES
        ) AS ESTADO_PROCES 
            ON RTRIM(ESTADO_PROCES.COD_DEF_PROCES) = RTRIM(TAB1.COD_DEF_PROCES)
            AND RTRIM(ESTADO_PROCES.NUM_SEQ) = RTRIM(TAB1.NUM_SEQ_ESTADO)

-- ############################################ --
-- ## CONSULTA QUE RETORNA O NOME DE CADA ETAPA DO PROCESSO
SELECT
    TB1.COD_DEF_PROCES AS 'PROCESSO',
    TB1.NUM_SEQ AS 'NUM_ETAPA',
    TB1.NUM_SEQ AS 'SEQUENCIAL',
    TB1.NUM_VERS AS 'VERSÃO',
    TB1.DES_ESTADO AS 'NOME_ETAPA',
    TB1.DSL_INSTRUC AS 'INSTRUÇÃO',
    PW.NUM_PROCES AS 'NUM_PROCESSO',
    *,
    CONCAT(PW.NUM_PROCES,' - ',TB1.NUM_VERS,' - ',TB1.COD_DEF_PROCES) AS 'FX_ID'

    FROM ESTADO_PROCES AS TB1
    LEFT JOIN (
        SELECT COD_DEF_PROCES, MAX(NUM_PROCES) AS 'NUM_PROCES' FROM PROCES_WORKFLOW GROUP BY COD_DEF_PROCES) AS PW ON TB1.COD_DEF_PROCES=PW.COD_DEF_PROCES
    WHERE TB1.COD_EMPRESA = 1

-- CONSULTA DE SOLICITAÇÃO PELO NÚMERO
USE fluig_prod SELECT * FROM PROCES_WORKFLOW WHERE COD_EMPRESA = 1 AND NUM_PROCES = '99145'
-- STATUS
-- ATIVO = 0
-- CANCELADO = 1
-- FINALIZADO = 2

