-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR


SELECT *
FROM VERS_DEF_PROCES
WHERE COD_EMPRESA = 1 AND COD_DEF_PROCES = 'ABERTURA_FIC3'


-- ALTERAR LOG_ATIV DA ULTIMA VERSÃO PRA 0 PRA INATIVAR O PROCESSO --

-- UPDATE VERS_DEF_PROCES SET LOG_ATIV = 0 WHERE COD_EMPRESA = 1 AND LOG_ATIV = 1 AND COD_DEF_PROCES = 'ABERTURA_FIC3'