-- AUTHOR: MARCELLO QUEIROZ
-- DATE: 16/07/2022
-- VERSION: 01
-- CONTACT PHONE: 55 41 99249-1979
-- MAIL: contato@marcelloqueiroz.com.br
-- GITHUB: https://github.com/Mquefi
-- BRAZIL - CURITIBA - PR

SELECT
    *
FROM FDN_USER
    LEFT JOIN FDN_USERTENANT ON FDN_USER.USER_ID = FDN_USERTENANT.USER_ID
WHERE
    FDN_USERTENANT.TENANT_ID = 1 -- EMPRESA
    AND USER_TYPE = 0 -- 0: USUÁRIO NORMAL / 2: USUÁRIO DO SISTEMA
    AND USER_STATE = 1 -- 1: ATIVO / 2: BLOQUEADO
ORDER BY FULL_NAME
--SELECT TOP 5 * FROM FDN_USERTENANT